#!/usr/bin/env python3
"""Regenerate ``docs/commands.md`` from the real parser.

``--check`` compares without writing, so CI can fail on drift. The file is
generated: hand-edits are overwritten by the next run.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "commands.md"


def _collect() -> dict[tuple[str, ...], tuple[str, object]]:
    os.environ.setdefault("PROXMOX_AGENT_LAB_CONFIG",
                          str(ROOT / "tests" / "fixtures" / "config.toml"))
    sys.path.insert(0, str(ROOT / "src"))
    from proxmox_agent_lab import cli

    found: dict[tuple[str, ...], tuple[str, object]] = {}

    def walk(parser: object, prefix: tuple[str, ...]) -> None:
        subparsers = getattr(parser, "_subparsers", None)
        for action in getattr(subparsers, "_group_actions", []) or []:
            choices = getattr(action, "choices", None) or {}
            help_by_name = {
                choice.dest: getattr(choice, "help", "")
                for choice in getattr(action, "_choices_actions", [])
            }
            for name, sub in choices.items():
                path = prefix + (name,)
                found[path] = (help_by_name.get(name, ""), sub)
                if sub is not None:
                    walk(sub, path)

    walk(cli.parser(), ())
    return found


def render(found: dict[tuple[str, ...], tuple[str, object]]) -> str:
    out = [
        "<!-- generated by scripts/gen-commands.py -- do not edit by hand -->",
        "",
        "# Command reference",
        "",
        "Every `proxmox-lab` subcommand, generated from the parser. Flag-level",
        "detail belongs to `--help` and the feature pages listed in",
        "[README.md](README.md); this is the map.",
        "",
    ]
    top = sorted({path[0] for path in found if len(path) == 1})
    for top_name in top:
        help_text, _ = found[(top_name,)]
        out.append(f"## `proxmox-lab {top_name}`")
        out.append("")
        if help_text:
            out.append(f"{help_text}")
            out.append("")
        children = sorted(path for path in found
                          if path[:-1] == (top_name,))
        for child in children:
            child_help, sub = found[child]
            line = f"- `proxmox-lab {' '.join(child)}`"
            if child_help:
                line += f" — {child_help}"
            out.append(line)
            # Third level, rare (e.g. net dhcp leases).
            for grandchild in sorted(p for p in found
                                     if p[:-1] == child):
                gc_help, _ = found[grandchild]
                gline = f"  - `proxmox-lab {' '.join(grandchild)}`"
                if gc_help:
                    gline += f" — {gc_help}"
                out.append(gline)
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    content = render(_collect())
    if "--check" in sys.argv:
        current = DOC.read_text() if DOC.exists() else ""
        if current != content:
            print("docs/commands.md is stale -- run scripts/gen-commands.py")
            return 1
        print("docs/commands.md is up to date")
        return 0
    DOC.write_text(content)
    print(f"wrote {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
